#!/bin/sh

# GatsD New Site
# Build docker with tag
# If no package.json - download new site
# Delete package-lock.json && yarn run install --force

. "$(dirname $0)/_default.conf"


##### FLAGS #####
tag=${BUILD_TAG}		# flag -t
port=${GATSBY_PORT}		# flag -p
host=${GATSBY_HOST}		# flag -H

if [ "$1" == "new" ]; then
	shift
fi

while getopts ":H:p:t:" flag; do
	case "${flag}" in
		H) 
			host="${OPTARG}"
			;;
		p) 
			port="${OPTARG}"
			;;
		t) 
			tag="${OPTARG}"
			;;
		*) 
			echo "ERROR: Invalid flag ${flag}"
			exit 1
			;;
	esac
done
shift `expr $OPTIND - 1`
if [ "$1" == "new" ]; then
	shift
fi


##### CONSTANTS #####
SITE_NAME=${SITE_NAME}
GATSD_VERSION=${GATSD_VERSION}

echo "0: $0"
echo "@: $@"
echo "OPTIND: $OPTIND"
echo "host: $host"
echo "port: $port"
echo "tag: $tag"


echo "Starting to build docker container"
$(dirname $0)/docker-build -t "${tag}" -H "${host}" -p "${port}" || exit 1

echo "Initializing project."
$(dirname $0)/run gatsd new -H "${host}" -p "${port}" $@ || exit 1