#!/bin/sh

# GatsD Run
# Call from host project dir to run any command in Docker container.

# shellcheck source=gatsd/_build-env
. "$(dirname $0)/_build-env"

docker run \
	-it \
	-p "${GATSBY_PORT}:${GATSBY_PORT}" \
	-u $(id -u):$(id -g) \
	-v "${GATSBY_DIR}:${WORK_DIR}" \
	"${TAG_NAME}" \
	$@
